"""
PDF Report Generator — branded Jawda KPI reports.
Uses fpdf2 (pure Python, zero system deps).
"""
import io
import hashlib
from datetime import datetime
from fpdf import FPDF


ACTION_FIXES = {
    "OMC001": "Add drug_name column with medication names from pharmacy.",
    "OMC002": "Include prescription data within 3 days of bronchitis visits.",
    "OMC003": "Capture registration + consult-start timestamps.",
    "OMC004": "Add management_plan field for BMI counselling documentation.",
    "OMC005": "Integrate HbA1c lab results (CPT 83036) into HIS export.",
    "OMC006": "Ensure HTN patients have confirmed ICD codes (I10-I13).",
    "OMC007": "Add days_supplied to pharmacy export for threshold calc.",
    "OMC008": "Integrate eGFR and uACR lab results into HIS export.",
}


def _verdict_label(v):
    return {"ready": "Ready for Submission", "attention": "Needs Attention", "not_ready": "Not Ready"}.get(v, "Unknown")


def _result_label(kpi):
    if kpi.get("meets_target") is True: return "PASS"
    if kpi.get("meets_target") is False: return "FAIL"
    if kpi.get("status") == "not_applicable": return "N/A"
    if kpi.get("status") == "insufficient_data": return "NO DATA"
    return "PROXY"


class JawdaPDF(FPDF):
    def __init__(self, facility_name, quarter):
        super().__init__()
        self.facility_name = facility_name
        self.quarter = quarter
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Navy header bar
        self.set_fill_color(13, 33, 55)  # navy-500
        self.rect(0, 0, 210, 28, 'F')
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 6)
        self.cell(0, 8, self.facility_name, ln=False)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(180, 200, 220)
        self.set_xy(10, 16)
        self.cell(0, 6, f'DOH Jawda KPI Report  |  {self.quarter}  |  ADHICS V2 Compliant  |  UAE North', ln=False)
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', '', 7)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f'Generated by Jawda KPI Platform by TriZodiac  |  {datetime.now().strftime("%d %b %Y %H:%M")}  |  Page {self.page_no()}', align='C')

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(13, 33, 55)
        self.cell(0, 8, title, ln=True)
        # Teal underline
        self.set_draw_color(20, 184, 166)
        self.set_line_width(0.6)
        self.line(self.get_x(), self.get_y(), self.get_x() + 40, self.get_y())
        self.ln(4)


def generate_pdf(facility_name, quarter, kpis, summary, history=None,
                  generated_by="", branding=None):
    """Generate PDF bytes from KPI results."""
    pdf = JawdaPDF(facility_name, quarter)
    pdf.add_page()

    na = summary.get("not_applicable", 0)
    meeting = summary.get("meeting_target", 0)
    below = summary.get("below_target", 0)
    insuff = summary.get("missing_data", 0)
    verdict = summary.get("verdict", "not_ready")
    readiness = summary.get("readiness_pct", 0)

    # ── Verdict Box ──
    v_colors = {
        "ready": (5, 150, 105, 236, 253, 245),
        "attention": (217, 119, 6, 255, 251, 235),
        "not_ready": (220, 38, 38, 254, 242, 242),
    }
    tr, tg, tb, br, bg, bb = v_colors.get(verdict, (100, 100, 100, 245, 245, 245))
    pdf.set_fill_color(br, bg, bb)
    pdf.rect(10, pdf.get_y(), 190, 18, 'F')
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(tr, tg, tb)
    pdf.set_xy(15, pdf.get_y() + 2)
    pdf.cell(0, 7, _verdict_label(verdict))
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.set_xy(15, pdf.get_y() + 8)
    pdf.cell(0, 5, f'{meeting}/8 passing  |  {below} below target  |  {na} N/A  |  {insuff} insufficient  |  Readiness: {readiness}%')
    pdf.ln(14)

    # ── Summary Stats ──
    pdf.ln(2)
    stat_y = pdf.get_y()
    stats = [
        (meeting, "Passing", 5, 150, 105),
        (below, "Below Target", 220, 38, 38),
        (na, "N/A", 37, 99, 235),
        (f"{readiness}%", "Readiness", 13, 33, 55),
    ]
    col_w = 47
    for i, (val, label, r, g, b) in enumerate(stats):
        x = 10 + i * (col_w + 1)
        pdf.set_fill_color(249, 250, 251)
        pdf.rect(x, stat_y, col_w, 16, 'DF')
        pdf.set_font('Helvetica', 'B', 18)
        pdf.set_text_color(r, g, b)
        pdf.set_xy(x, stat_y + 1)
        pdf.cell(col_w, 8, str(val), align='C')
        pdf.set_font('Helvetica', 'B', 6)
        pdf.set_text_color(160, 160, 160)
        pdf.set_xy(x, stat_y + 10)
        pdf.cell(col_w, 4, label.upper(), align='C')
    pdf.set_y(stat_y + 20)

    # ── KPI Results Table ──
    pdf.section_title('KPI Results')
    kpi_order = ["OMC001", "OMC002", "OMC003", "OMC004", "OMC005", "OMC006", "OMC007", "OMC008"]

    # Table header
    pdf.set_font('Helvetica', 'B', 7)
    pdf.set_fill_color(243, 244, 246)
    pdf.set_text_color(107, 114, 128)
    headers = ['KPI', 'Title', 'Domain', 'Num', 'Den', 'Rate', 'Target', 'Result']
    widths = [14, 52, 24, 14, 14, 16, 16, 16]
    # Calculate starting x to center the table
    total_w = sum(widths)
    start_x = (210 - total_w) / 2
    for i, (h, w) in enumerate(zip(headers, widths)):
        pdf.set_x(start_x + sum(widths[:i]))
        pdf.cell(w, 6, h, border=1, align='C', fill=True)
    pdf.ln()

    # Table rows
    pdf.set_font('Helvetica', '', 8)
    for kpi_id in kpi_order:
        k = kpis.get(kpi_id, {})
        den = k.get("denominator", 0)
        pct = f"{k.get('percentage', 0)}%" if den > 0 else "—"
        target = k.get("target", 0)
        direction = k.get("target_direction", "higher")
        dir_sym = "≤" if direction == "lower" else "≥"
        result = _result_label(k)

        # Result color
        if k.get("meets_target") is True:
            pdf.set_text_color(5, 150, 105)
        elif k.get("meets_target") is False:
            pdf.set_text_color(220, 38, 38)
        elif k.get("status") == "not_applicable":
            pdf.set_text_color(37, 99, 235)
        else:
            pdf.set_text_color(107, 114, 128)

        row_data = [
            (kpi_id, 'L', True),
            (k.get('title', '')[:30], 'L', False),
            (k.get('domain', '')[:12], 'C', False),
            (str(k.get('numerator', 0)), 'C', False),
            (str(den), 'C', False),
            (pct, 'C', True),
            (f"{dir_sym}{target}%", 'C', False),
            (result, 'C', True),
        ]
        for i, (val, align, bold) in enumerate(row_data):
            pdf.set_x(start_x + sum(widths[:i]))
            if i == 0:
                pdf.set_font('Helvetica', 'B', 8)
                pdf.set_text_color(13, 33, 55)
            elif i == len(row_data) - 1:
                # Result cell uses color set above
                if k.get("meets_target") is True:
                    pdf.set_text_color(5, 150, 105)
                elif k.get("meets_target") is False:
                    pdf.set_text_color(220, 38, 38)
                elif k.get("status") == "not_applicable":
                    pdf.set_text_color(37, 99, 235)
                else:
                    pdf.set_text_color(107, 114, 128)
                pdf.set_font('Helvetica', 'B', 8)
            else:
                pdf.set_font('Helvetica', 'B' if bold else '', 8)
                pdf.set_text_color(55, 65, 81)
            pdf.cell(widths[i], 6, val, border=1, align=align)
        pdf.ln()

    pdf.set_text_color(0, 0, 0)

    # ── Action Plan ──
    failing = [(kpi_id, kpis[kpi_id]) for kpi_id in kpi_order
               if kpis.get(kpi_id, {}).get("meets_target") is False]
    if failing:
        pdf.ln(4)
        pdf.section_title('Action Plan')
        pdf.set_font('Helvetica', '', 8)
        for kpi_id, k in failing:
            gap = k.get("gap_patients", 0)
            fix = ACTION_FIXES.get(kpi_id, "Review data quality.")
            pdf.set_font('Helvetica', 'B', 8)
            pdf.set_text_color(220, 38, 38)
            pdf.cell(14, 5, kpi_id)
            pdf.set_text_color(13, 33, 55)
            pdf.cell(50, 5, k.get('title', '')[:28])
            pdf.set_font('Helvetica', '', 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(20, 5, f'{k.get("percentage", 0)}% vs {k.get("target", 0)}%')
            pdf.cell(15, 5, f'Gap: {gap}')
            pdf.ln()
            pdf.set_font('Helvetica', '', 7)
            pdf.set_text_color(80, 80, 80)
            pdf.set_x(24)
            pdf.multi_cell(165, 4, fix)
            pdf.ln(1)

    # ── Quarter History ──
    if history and len(history) > 1:
        pdf.ln(4)
        pdf.section_title('Quarter History')
        pdf.set_font('Helvetica', 'B', 7)
        pdf.set_fill_color(243, 244, 246)
        pdf.set_text_color(107, 114, 128)
        for h, w in [('Quarter', 30), ('Passing', 25), ('Verdict', 40)]:
            pdf.cell(w, 5, h, border=1, align='C', fill=True)
        pdf.ln()
        pdf.set_font('Helvetica', '', 8)
        for q in sorted(history.keys()):
            s = history[q].get("jawda_summary", {})
            m = s.get("meeting_target", 0)
            v = s.get("verdict", "")
            pdf.set_text_color(13, 33, 55)
            pdf.set_font('Helvetica', 'B', 8)
            pdf.cell(30, 5, q, border=1, align='C')
            pdf.set_font('Helvetica', '', 8)
            pdf.cell(25, 5, f'{m}/8', border=1, align='C')
            # Verdict color
            vc = {"ready": (5, 150, 105), "attention": (217, 119, 6), "not_ready": (220, 38, 38)}.get(v, (100, 100, 100))
            pdf.set_text_color(*vc)
            pdf.set_font('Helvetica', 'B', 8)
            pdf.cell(40, 5, _verdict_label(v), border=1, align='C')
            pdf.ln()

    # Output
    pdf_bytes = pdf.output()
    report_hash = hashlib.sha256(pdf_bytes).hexdigest()[:16]
    return bytes(pdf_bytes), report_hash
